version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run data analysis script
          command: python scripts/data_analysis.py

      - run:
          name: Run unit tests
          command: pytest tests/

workflows:
  version: 2
  test-and-build:
    jobs:
      - test